### ISSUE TITLE
Vulnerability data unavailable for inline scanning

### ISSUE THREAD

**Issue by targeter21** [anchore/ci-tools#14]
Hi, using the following command for a local image based on UBI8:
```
curl -s https://ci-tools.anchore.io/inline_scan-v0.3.3 | bash -s --  -t 500 -f <image name>
```
I receive the following for vulnerabilities:
```
Gate                   Trigger                               Detail                                                                                     Status
vulnerabilities        stale_feed_data                       The vulnerability feed for this image distro is older than MAXAGE (2) days                 warn          
vulnerabilities        vulnerability_data_unavailable        Feed data unavailable, cannot perform CVE scan for distro: rhel:8.0                        warn
```

Is there a way to update the data for the inline scanning?

**Comment by targeter21** [comment]
Thanks!

**Comment by zhill** [comment]
So the issue looks like you're trying to analyze a rhel/centos 8 image. Digging into the RHEL vuln data it looks like they have not yet merged the RHEL8 data into their unified OVAL XML file, which is the one we use to gather the data for all RHEL releases. Once they do that merge we'll automatically pick it up and it will be available.

**Comment by targeter21** [comment]
Sounds good! I'll close this out then.
