### ISSUE TITLE
Get CircleCI Orb certified

### ISSUE THREAD

**Issue by AndreasKnapp1812** [anchore/ci-tools#15]
Hello,
I don't know about the process of certifying circleci orbs, but is there a chance to get the anchore-engine orb certified?

**Comment by Btodhunter** [comment]
Hey @AndreasKnapp1812, thanks for pointing this out. Only orbs maintained by CircleCI get the 'certified' label. We've gone through the process of becoming a 'partner' orb, which is the best we can do for now. If CircleCI ever gives partner orbs the chance to become certified, we'll definitely jump at the opportunity!

**Comment by AndreasKnapp1812** [comment]
oh I haven't realized that, thanks for for pointing it out @Btodhunter .
