### ISSUE TITLE
vulnerabilities data older than 10 days

### ISSUE THREAD

**Issue by jorgensoares** [anchore/ci-tools#16]
Hello,

You state that the vuln database is updated daily but running the inline scan i get the alert the data is older than 10 days. I running the scan agains a debian based image.

Thank you!

**Comment by Btodhunter** [comment]
Hey @jorgensoares, thanks for submitting this issue! Our engine-db-preload job was failing for a few days, which was causing the inline scans vuln database to not get update. That job is now fixed. If you pull the latest inline_scan image you should have the most up to date vuln database.

You can see our daily update jobs at https://circleci.com/gh/anchore/ci-tools & https://circleci.com/gh/anchore/engine-db-preload

**Comment by jorgensoares** [comment]
Thank you very much! keep the good work! :)
