### ISSUE TITLE
vuln feeds haven't been updated for anchore-inline image since at least nov 29

### ISSUE THREAD

**Issue by tonkapango** [anchore/ci-tools#21]
The problem
---
The vulnerability feeds (nvd, canonical, etc) appear to be stale.

Environment
---

Details
---

Actual Behaviour
---

Expected Behaviour
---

How do you reproduce the error?
---

**Comment by Btodhunter** [comment]
@tonkapango Thanks for pointing this out. We're aware of the issue, our nightly preload DB job has been having some issues due to the large number of updates to the vulnerability feeds, which is causing our CI system to OOM & fail. I'm working on a fix and plan to get this resolved ASAP.

**Comment by Btodhunter** [comment]
I was able to fix the db-preload nightly job and the inline-scan container is getting updated with the newest vulnerabilities again.

**Comment by tonkapango** [comment]
thanks!
